# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_address',
            field=models.CharField(default='0.0.0.0', max_length=100),
            preserve_default=False,
        ),
    ]
