# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_sensor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMP180',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('altitude', models.FloatField()),
            ],
            bases=('sensors.sensor',),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('T', 'Temperature'), ('P', 'Pressure')], max_length=10)),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor'),
        ),
    ]
